// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package judge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OJServerError-10001]
	_ = x[CompileError-20001]
	_ = x[SubmitError-20002]
	_ = x[UnsupportedLanguageError-20003]
}

const (
	_ErrCode_name_0 = "OJServerError"
	_ErrCode_name_1 = "CompileErrorSubmitErrorUnsupportedLanguageError"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 12, 23, 47}
)

func (i ErrCode) String() string {
	switch {
	case i == 10001:
		return _ErrCode_name_0
	case 20001 <= i && i <= 20003:
		i -= 20001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
